- name: Patch Red Hat Enterprise Linux system
  hosts: all
  gather_facts: False
  ignore_errors: True
  tasks:
    - name: Update all RPM packages
      yum:
        name: '*'
        state: latest
      become: yes
      register: patched
      
    - name: Reboot the system when software has been updated
      reboot:
      when: patched is changed
      
    - name: Check so that server is online
      wait_for:
        port: 22
        search_regex: OpenSSH
      vars:
        ansible_connection: local
